import { useAppSelector, useAppDispatch } from 'src/redux/hook'
import { decrement, increment } from 'src/redux/counterSlice'

import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const count = useAppSelector((state) => state.counter.value)
  const dispatch = useAppDispatch()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            RTK basic config&nbsp;
            <code className={styles.code}>src/redux/store.ts</code>
          </p>
          <div>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
          </div>
        </div>

        <div className='card' style={{width: 200, marginBottom: 10}}>
          {/* My code here */}
          <button style={{margin: 15, fontSize: 30}} className='btn btn-light'>{count}</button>
        </div>
            <button style={{ width: 200, margin: 5}} className='btn btn-primary' onClick={()=> dispatch(increment())}>+1</button>

            <button style={{ width: 200, margin: 5}} className='btn btn-danger' onClick={()=> dispatch(decrement())}>-1</button>
      </main>
    </>
  )
}
